### ISSUE TITLE
External arguer

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#10]
move argue logic out of Model, as discussed

**Comment by tonyseg** [comment]
Done.

**Comment by oliviercailloux** [comment]
This is not exactly as discussed. Ok to simplify it, though. But the current `argue` is too complex, and the logic is unclear as possible usage depends on how the class has been initialized.

Please provide methods `argueIVT(IVTOutput output)`, `argueRMGAVG(RMGAVTOutput)`, … and `argue(LabreucheOutput)` which delegates to the right method using a switch.

**Comment by tonyseg** [comment]
Done.

**Comment by oliviercailloux** [comment]
Nice. Please call it LabreucheArguer (move it to the corresponding package) and create another NunesArguer for Nunes model.

**Comment by tonyseg** [comment]
Done.

**Comment by oliviercailloux** [comment]
`LabreucheArguer` should be in package, well, `labreuche`. (Similarly for Nunes.)
The method should not return a string to indicate an error, it should fail fast and in a detectable way by throwing an exception. It should be an `IllegalStateException` in case of an impossible default case in a switch (in `LabreucheArguer`) and an `UnsupportedOperationException` in case of not yet implemented part functionality (in `NunesArguer`).

**Comment by tonyseg** [comment]
Migration on the right package and `IllegalStateException` throwing in default case.

**Comment by tonyseg** [comment]
Done
