### ISSUE TITLE
x and y in AltsComp

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#13]
Think about how to treat x and y. Do not swap them silently.

**Comment by tonyseg** [comment]
I swipe them if the x given is not better than y, because we suppose : x is better than y for the explanation. This is just a seatbelt if x and y given are not in the right order.

**Comment by oliviercailloux** [comment]
Please maake sure that the documentation of `AlternativesComparison` matches the code. Currently the code checks that the weights are not null and not empty, but this is not documented; the documentation requires that x and y do not have the same evaluation but this is not checked.

BTW, replace documentation to say that x must be better than y, and check this in the code. It is too surprising for the user to replace x and y without the user having asked it.
