### ISSUE TITLE
Simplify Criterion

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#16]
Please rename the current `Criterion` to `CriterionWithScale` so that all code in the `uta_calculator` packages use `CriterionWithScale`. Create another class, `io.github.oliviercailloux.decision.model.Criterion`, immutable, with only a name and id (no scale). Your classes (in the `decision` packages) should use `Criterion` and not `CriterionWithScale`.
Similarly, rename the `Alternative` to `UTAAlternative`, which uses `CriterionWithScale`, and create another one, `EvaluatedAlternative`, which uses `Criterion` and which the code in `decision` uses.

**Comment by tonyseg** [comment]
Done. `io.github.oliviercailloux.decision.model.ProblemGenerator` added, it use `Criterion` and `EvaluatedAlternative` instead of `CriterionWithScale` and `UTAAlternative`.
