### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#3]
Use SLF4J instead of `System.out`. See [example](https://github.com/oliviercailloux/java-se-1.8-archetype).

**Comment by oliviercailloux** [comment]
Plz change initialization to systematically follow the given example.

**Comment by oliviercailloux** [comment]
Uncomment logs, put in debug level instead of info if you want to hide them.

**Comment by tonyseg** [comment]
Fixed

**Comment by oliviercailloux** [comment]
Good job. Small detail: name the variables `LOGGER`, as it is static final as a constant.

**Comment by tonyseg** [comment]
logger to LOGGER fixed
