### ISSUE TITLE
Test uta

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#5]
Let test uta pass by configuring Maven properly.
Depend on google-or-tools version 6.7.2 and see config `maven-surefire-plugin` [here](https://github.com/oliviercailloux/google-or-tools-java/blob/master/pom.xml).
Remove unused library files (see above project).
Simplify README.

**Comment by tonyseg** [comment]
I have an DependencyResolutionException when I  launch "mvn test" : Maven could not find artifact io.github.oliviercailloux:google-or-tools:jar:6.7.2.a-SNAPSHOT, I try the solution given in [here](https://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException) but I did'nt what to do in settings.xml.

**Comment by oliviercailloux** [comment]
Depend on google-or-tools version 6.7.2 (not 6.7.2.a-SNAPSHOT, not published)

**Comment by tonyseg** [comment]
Fixed "mvn test" working now.

**Comment by oliviercailloux** [comment]
Simplify README (for example, no need for protobuf library now that it is a dependency in Maven).

**Comment by oliviercailloux** [comment]
Well done.
