### ISSUE TITLE
IVTOutput graph building

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#7]
`computeKset()`: Use builder ; don’t copy the graph after building

**Comment by tonyseg** [comment]
The method used to craft graph kPN is the method given in guava's doc :

"You create an instance of an ImmutableGraph, etc. by calling its static copyOf() method:
ImmutableGraph<Integer> immutableGraph = ImmutableGraph.copyOf(graph);"

**Comment by oliviercailloux** [comment]
T’as raison !
