### ISSUE TITLE
Asciidoc

### ISSUE THREAD

**Issue by oliviercailloux** [oliviercailloux/decision-uta-method#8]
Simplify README and transform it to Asciidoctor format.
(First solve https://github.com/oliviercailloux/decision-uta-method/issues/5)

**Comment by oliviercailloux** [comment]
Simplify README (for example, no need for protobuf library now that it is a dependency in Maven).

**Comment by oliviercailloux** [comment]
Remove unused lib files: I believe only `libjniortools.so` and `libortools.so` are useful on Linux, and most probably only the dll file is useful on Windows

Indicate in README where the lib files come from precisely.

**Comment by tonyseg** [comment]
README updated and lib repository lighted

**Comment by oliviercailloux** [comment]
Thx, that’s clear.
